name: piwigo_ng
description: A Piwigo Android application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+103

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:

  # Icons :
  font_awesome_flutter: ^9.2.0

  # Requests :
  dio: ^4.0.3
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1

  # Upload and download :
  chunked_uploader: ^0.1.0
  flutter_absolute_path:
    git:
      url: https://github.com/canewsin/flutter_absolute_path.git
  path_provider: ^2.0.7
  permission_handler: ^8.3.0
  ext_storage: ^1.0.3 # Deprecated
  external_path: ^1.0.1
  flutter_local_notifications: ^9.1.2

  # File pickers :
  image_picker: ^0.8.4+4
  file_picker: ^4.2.4
  provider: ^6.0.1

  # Local storage :
  shared_preferences: ^2.0.8
  package_info_plus: ^1.3.0
  flutter_secure_storage: ^5.0.2

  # Widgets :
  url_launcher: ^6.0.12
  webview_flutter: ^2.3.1
  flutter_speed_dial: ^4.6.6
  icon_shadow: ^1.0.1
  flutter_slidable: ^1.1.0
  auto_size_text: ^3.0.0
  sliding_up_panel: ^2.0.0+1

  # Media :
  photo_view: ^0.9.0
  cached_network_image: ^3.0.0
  better_player: ^0.0.79
  wakelock: ^0.5.6
  mime_type: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  dependency_validator: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  generate: true

  uses-material-design: true

  assets:
    - assets/logo/piwigo_logo.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
