name: Build Debug

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.6'

      - run: |
          set -eu
          flutter config --no-analytics
          flutter pub get

      - name: Build app
        run: flutter build apk --debug --no-shrink

      - name: Upload artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: piwigo-app
          path: build/app/outputs/flutter-apk/app-debug.apk
