name: Build Debug

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build Debug
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0

      - name: Fetch dependencies
        run: |
          set -eu
          flutter config --no-analytics
          flutter pub get

      - name: Build app
        run: |
          set -eu
          flutter build apk --debug --no-shrink

      - name: Upload artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: piwigo-app
          path: build/app/outputs/flutter-apk/app-debug.apk
